# Wardrobe: clothing libraries on the ten bodies of the gallery, bare then dressed, one scenario per mod. Generated by gen-wardrobe.js; do not edit by hand.
# Every image is opened and read: the question is whether the garment looks right on the body, with and without this mod's cut.
# Pass: wsl-deps.wardrobe.map.
@review @wardrobe @timeout:300
Feature: clothing libraries on the ten bodies

  Background:
    Given the save "Nelims-tribe" is loaded

  @requires:wdi.realistic.bodies @requires:nelim.pickletools.screenshotstudio @requires:nelim.pickletools.colonistrace @requires:UNAGI.Ap.Dress
  Scenario: UNAGI Royalty Apparel on ten bodies
    Given Nelim's Sanctuary: the animals are removed from the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: the other colonists are out of frame
    And a colonist "M-Thin" exists
    And "M-Thin" gender is male
    And Nelim's Pickle Tools: "M-Thin" body type is Thin
    And a colonist "M-Avg" exists
    And "M-Avg" gender is male
    And Nelim's Pickle Tools: "M-Avg" body type is Male
    And a colonist "M-Fat" exists
    And "M-Fat" gender is male
    And Nelim's Pickle Tools: "M-Fat" body type is Fat
    And a colonist "M-Hulk" exists
    And "M-Hulk" gender is male
    And Nelim's Pickle Tools: "M-Hulk" body type is Hulk
    And a colonist "M-Kid" exists
    And "M-Kid" is 8 years old
    And "M-Kid" gender is male
    And Nelim's Pickle Tools: "M-Kid" body type is Child
    And a colonist "F-Thin" exists
    And "F-Thin" gender is female
    And Nelim's Pickle Tools: "F-Thin" body type is Thin
    And a colonist "F-Avg" exists
    And "F-Avg" gender is female
    And Nelim's Pickle Tools: "F-Avg" body type is Female
    And a colonist "F-Fat" exists
    And "F-Fat" gender is female
    And Nelim's Pickle Tools: "F-Fat" body type is Fat
    And a colonist "F-Hulk" exists
    And "F-Hulk" gender is female
    And Nelim's Pickle Tools: "F-Hulk" body type is Hulk
    And a colonist "F-Kid" exists
    And "F-Kid" is 8 years old
    And "F-Kid" gender is female
    And Nelim's Pickle Tools: "F-Kid" body type is Child
    And Nelim's Pickle Tools: "M-Thin" stands at (196, 186) facing South
    And I draft "M-Thin"
    And Nelim's Pickle Tools: "M-Avg" stands at (198, 186) facing South
    And I draft "M-Avg"
    And Nelim's Pickle Tools: "M-Fat" stands at (200, 186) facing South
    And I draft "M-Fat"
    And Nelim's Pickle Tools: "M-Hulk" stands at (202, 186) facing South
    And I draft "M-Hulk"
    And Nelim's Pickle Tools: "M-Kid" stands at (204, 186) facing South
    And I draft "M-Kid"
    And Nelim's Pickle Tools: "F-Thin" stands at (196, 184) facing South
    And I draft "F-Thin"
    And Nelim's Pickle Tools: "F-Avg" stands at (198, 184) facing South
    And I draft "F-Avg"
    And Nelim's Pickle Tools: "F-Fat" stands at (200, 184) facing South
    And I draft "F-Fat"
    And Nelim's Pickle Tools: "F-Hulk" stands at (202, 184) facing South
    And I draft "F-Hulk"
    And Nelim's Pickle Tools: "F-Kid" stands at (204, 184) facing South
    And I draft "F-Kid"
    When I destroy the gear of "M-Thin"
    And I destroy the gear of "M-Avg"
    And I destroy the gear of "M-Fat"
    And I destroy the gear of "M-Hulk"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And I destroy the gear of "F-Avg"
    And I destroy the gear of "F-Fat"
    And I destroy the gear of "F-Hulk"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: studio presentation mode is enabled
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi royalty apparel, bare"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_UNARoyalDress"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_UNARoyalDress"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_UNARoyalDress"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_UNARoyalDress"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_UNARoyalDress"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_UNARoyalDress"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_UNARoyalDress"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_UNARoyalDress"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi royalty apparel, Apparel_UNARoyalDress"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_UNA_dressR"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_UNA_dressR"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_UNA_dressR"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_UNA_dressR"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_UNA_dressR"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_UNA_dressR"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_UNA_dressR"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_UNA_dressR"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi royalty apparel, Apparel_UNA_dressR"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_UNA_gothicdress"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_UNA_gothicdress"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_UNA_gothicdress"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_UNA_gothicdress"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_UNA_gothicdress"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_UNA_gothicdress"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_UNA_gothicdress"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_UNA_gothicdress"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi royalty apparel, Apparel_UNA_gothicdress"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "UNA_MstyleShirtpants"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "UNA_MstyleShirtpants"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "UNA_MstyleShirtpants"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "UNA_MstyleShirtpants"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "UNA_MstyleShirtpants"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "UNA_MstyleShirtpants"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "UNA_MstyleShirtpants"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "UNA_MstyleShirtpants"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi royalty apparel, UNA_MstyleShirtpants"

  @requires:wdi.realistic.bodies @requires:nelim.pickletools.screenshotstudio @requires:nelim.pickletools.colonistrace @requires:UNAGI.Battle.coat
  Scenario: UNAGI Battle Coat on ten bodies
    Given Nelim's Sanctuary: the animals are removed from the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: the other colonists are out of frame
    And a colonist "M-Thin" exists
    And "M-Thin" gender is male
    And Nelim's Pickle Tools: "M-Thin" body type is Thin
    And a colonist "M-Avg" exists
    And "M-Avg" gender is male
    And Nelim's Pickle Tools: "M-Avg" body type is Male
    And a colonist "M-Fat" exists
    And "M-Fat" gender is male
    And Nelim's Pickle Tools: "M-Fat" body type is Fat
    And a colonist "M-Hulk" exists
    And "M-Hulk" gender is male
    And Nelim's Pickle Tools: "M-Hulk" body type is Hulk
    And a colonist "M-Kid" exists
    And "M-Kid" is 8 years old
    And "M-Kid" gender is male
    And Nelim's Pickle Tools: "M-Kid" body type is Child
    And a colonist "F-Thin" exists
    And "F-Thin" gender is female
    And Nelim's Pickle Tools: "F-Thin" body type is Thin
    And a colonist "F-Avg" exists
    And "F-Avg" gender is female
    And Nelim's Pickle Tools: "F-Avg" body type is Female
    And a colonist "F-Fat" exists
    And "F-Fat" gender is female
    And Nelim's Pickle Tools: "F-Fat" body type is Fat
    And a colonist "F-Hulk" exists
    And "F-Hulk" gender is female
    And Nelim's Pickle Tools: "F-Hulk" body type is Hulk
    And a colonist "F-Kid" exists
    And "F-Kid" is 8 years old
    And "F-Kid" gender is female
    And Nelim's Pickle Tools: "F-Kid" body type is Child
    And Nelim's Pickle Tools: "M-Thin" stands at (196, 186) facing South
    And I draft "M-Thin"
    And Nelim's Pickle Tools: "M-Avg" stands at (198, 186) facing South
    And I draft "M-Avg"
    And Nelim's Pickle Tools: "M-Fat" stands at (200, 186) facing South
    And I draft "M-Fat"
    And Nelim's Pickle Tools: "M-Hulk" stands at (202, 186) facing South
    And I draft "M-Hulk"
    And Nelim's Pickle Tools: "M-Kid" stands at (204, 186) facing South
    And I draft "M-Kid"
    And Nelim's Pickle Tools: "F-Thin" stands at (196, 184) facing South
    And I draft "F-Thin"
    And Nelim's Pickle Tools: "F-Avg" stands at (198, 184) facing South
    And I draft "F-Avg"
    And Nelim's Pickle Tools: "F-Fat" stands at (200, 184) facing South
    And I draft "F-Fat"
    And Nelim's Pickle Tools: "F-Hulk" stands at (202, 184) facing South
    And I draft "F-Hulk"
    And Nelim's Pickle Tools: "F-Kid" stands at (204, 184) facing South
    And I draft "F-Kid"
    When I destroy the gear of "M-Thin"
    And I destroy the gear of "M-Avg"
    And I destroy the gear of "M-Fat"
    And I destroy the gear of "M-Hulk"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And I destroy the gear of "F-Avg"
    And I destroy the gear of "F-Fat"
    And I destroy the gear of "F-Hulk"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: studio presentation mode is enabled
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi battle coat, bare"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Thin" wears "UNA_MaidBattleArmor"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Avg" wears "UNA_MaidBattleArmor"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Fat" wears "UNA_MaidBattleArmor"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Hulk" wears "UNA_MaidBattleArmor"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Thin" wears "UNA_MaidBattleArmor"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Avg" wears "UNA_MaidBattleArmor"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Fat" wears "UNA_MaidBattleArmor"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Hulk" wears "UNA_MaidBattleArmor"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi battle coat, UNA_MaidBattleArmor"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Thin" wears "UNA_FlakDress"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Avg" wears "UNA_FlakDress"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Fat" wears "UNA_FlakDress"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Hulk" wears "UNA_FlakDress"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Thin" wears "UNA_FlakDress"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Avg" wears "UNA_FlakDress"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Fat" wears "UNA_FlakDress"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Hulk" wears "UNA_FlakDress"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi battle coat, UNA_FlakDress"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Thin" wears "UNA_PlateDress"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Avg" wears "UNA_PlateDress"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Fat" wears "UNA_PlateDress"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Hulk" wears "UNA_PlateDress"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Thin" wears "UNA_PlateDress"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Avg" wears "UNA_PlateDress"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Fat" wears "UNA_PlateDress"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Hulk" wears "UNA_PlateDress"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi battle coat, UNA_PlateDress"

  @requires:wdi.realistic.bodies @requires:nelim.pickletools.screenshotstudio @requires:nelim.pickletools.colonistrace @requires:UNAGI.huyuhuku.SET
  Scenario: UNAGI Winter clothing on ten bodies
    Given Nelim's Sanctuary: the animals are removed from the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: the other colonists are out of frame
    And a colonist "M-Thin" exists
    And "M-Thin" gender is male
    And Nelim's Pickle Tools: "M-Thin" body type is Thin
    And a colonist "M-Avg" exists
    And "M-Avg" gender is male
    And Nelim's Pickle Tools: "M-Avg" body type is Male
    And a colonist "M-Fat" exists
    And "M-Fat" gender is male
    And Nelim's Pickle Tools: "M-Fat" body type is Fat
    And a colonist "M-Hulk" exists
    And "M-Hulk" gender is male
    And Nelim's Pickle Tools: "M-Hulk" body type is Hulk
    And a colonist "M-Kid" exists
    And "M-Kid" is 8 years old
    And "M-Kid" gender is male
    And Nelim's Pickle Tools: "M-Kid" body type is Child
    And a colonist "F-Thin" exists
    And "F-Thin" gender is female
    And Nelim's Pickle Tools: "F-Thin" body type is Thin
    And a colonist "F-Avg" exists
    And "F-Avg" gender is female
    And Nelim's Pickle Tools: "F-Avg" body type is Female
    And a colonist "F-Fat" exists
    And "F-Fat" gender is female
    And Nelim's Pickle Tools: "F-Fat" body type is Fat
    And a colonist "F-Hulk" exists
    And "F-Hulk" gender is female
    And Nelim's Pickle Tools: "F-Hulk" body type is Hulk
    And a colonist "F-Kid" exists
    And "F-Kid" is 8 years old
    And "F-Kid" gender is female
    And Nelim's Pickle Tools: "F-Kid" body type is Child
    And Nelim's Pickle Tools: "M-Thin" stands at (196, 186) facing South
    And I draft "M-Thin"
    And Nelim's Pickle Tools: "M-Avg" stands at (198, 186) facing South
    And I draft "M-Avg"
    And Nelim's Pickle Tools: "M-Fat" stands at (200, 186) facing South
    And I draft "M-Fat"
    And Nelim's Pickle Tools: "M-Hulk" stands at (202, 186) facing South
    And I draft "M-Hulk"
    And Nelim's Pickle Tools: "M-Kid" stands at (204, 186) facing South
    And I draft "M-Kid"
    And Nelim's Pickle Tools: "F-Thin" stands at (196, 184) facing South
    And I draft "F-Thin"
    And Nelim's Pickle Tools: "F-Avg" stands at (198, 184) facing South
    And I draft "F-Avg"
    And Nelim's Pickle Tools: "F-Fat" stands at (200, 184) facing South
    And I draft "F-Fat"
    And Nelim's Pickle Tools: "F-Hulk" stands at (202, 184) facing South
    And I draft "F-Hulk"
    And Nelim's Pickle Tools: "F-Kid" stands at (204, 184) facing South
    And I draft "F-Kid"
    When I destroy the gear of "M-Thin"
    And I destroy the gear of "M-Avg"
    And I destroy the gear of "M-Fat"
    And I destroy the gear of "M-Hulk"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And I destroy the gear of "F-Avg"
    And I destroy the gear of "F-Fat"
    And I destroy the gear of "F-Hulk"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: studio presentation mode is enabled
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi winter clothing, bare"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Thin" wears "UNAGIapaka"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Avg" wears "UNAGIapaka"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Fat" wears "UNAGIapaka"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Hulk" wears "UNAGIapaka"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Thin" wears "UNAGIapaka"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Avg" wears "UNAGIapaka"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Fat" wears "UNAGIapaka"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Hulk" wears "UNAGIapaka"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi winter clothing, UNAGIapaka"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Thin" wears "UNAGImohukepu"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Avg" wears "UNAGImohukepu"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Fat" wears "UNAGImohukepu"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Hulk" wears "UNAGImohukepu"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Thin" wears "UNAGImohukepu"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Avg" wears "UNAGImohukepu"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Fat" wears "UNAGImohukepu"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Hulk" wears "UNAGImohukepu"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi winter clothing, UNAGImohukepu"

  @requires:wdi.realistic.bodies @requires:nelim.pickletools.screenshotstudio @requires:nelim.pickletools.colonistrace @requires:UNAGI.suit.SET
  Scenario: UNAGI SimpleSuit on ten bodies
    Given Nelim's Sanctuary: the animals are removed from the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: the other colonists are out of frame
    And a colonist "M-Thin" exists
    And "M-Thin" gender is male
    And Nelim's Pickle Tools: "M-Thin" body type is Thin
    And a colonist "M-Avg" exists
    And "M-Avg" gender is male
    And Nelim's Pickle Tools: "M-Avg" body type is Male
    And a colonist "M-Fat" exists
    And "M-Fat" gender is male
    And Nelim's Pickle Tools: "M-Fat" body type is Fat
    And a colonist "M-Hulk" exists
    And "M-Hulk" gender is male
    And Nelim's Pickle Tools: "M-Hulk" body type is Hulk
    And a colonist "M-Kid" exists
    And "M-Kid" is 8 years old
    And "M-Kid" gender is male
    And Nelim's Pickle Tools: "M-Kid" body type is Child
    And a colonist "F-Thin" exists
    And "F-Thin" gender is female
    And Nelim's Pickle Tools: "F-Thin" body type is Thin
    And a colonist "F-Avg" exists
    And "F-Avg" gender is female
    And Nelim's Pickle Tools: "F-Avg" body type is Female
    And a colonist "F-Fat" exists
    And "F-Fat" gender is female
    And Nelim's Pickle Tools: "F-Fat" body type is Fat
    And a colonist "F-Hulk" exists
    And "F-Hulk" gender is female
    And Nelim's Pickle Tools: "F-Hulk" body type is Hulk
    And a colonist "F-Kid" exists
    And "F-Kid" is 8 years old
    And "F-Kid" gender is female
    And Nelim's Pickle Tools: "F-Kid" body type is Child
    And Nelim's Pickle Tools: "M-Thin" stands at (196, 186) facing South
    And I draft "M-Thin"
    And Nelim's Pickle Tools: "M-Avg" stands at (198, 186) facing South
    And I draft "M-Avg"
    And Nelim's Pickle Tools: "M-Fat" stands at (200, 186) facing South
    And I draft "M-Fat"
    And Nelim's Pickle Tools: "M-Hulk" stands at (202, 186) facing South
    And I draft "M-Hulk"
    And Nelim's Pickle Tools: "M-Kid" stands at (204, 186) facing South
    And I draft "M-Kid"
    And Nelim's Pickle Tools: "F-Thin" stands at (196, 184) facing South
    And I draft "F-Thin"
    And Nelim's Pickle Tools: "F-Avg" stands at (198, 184) facing South
    And I draft "F-Avg"
    And Nelim's Pickle Tools: "F-Fat" stands at (200, 184) facing South
    And I draft "F-Fat"
    And Nelim's Pickle Tools: "F-Hulk" stands at (202, 184) facing South
    And I draft "F-Hulk"
    And Nelim's Pickle Tools: "F-Kid" stands at (204, 184) facing South
    And I draft "F-Kid"
    When I destroy the gear of "M-Thin"
    And I destroy the gear of "M-Avg"
    And I destroy the gear of "M-Fat"
    And I destroy the gear of "M-Hulk"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And I destroy the gear of "F-Avg"
    And I destroy the gear of "F-Fat"
    And I destroy the gear of "F-Hulk"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: studio presentation mode is enabled
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi simplesuit, bare"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "UNAGInoEshirt"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "UNAGInoEshirt"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "UNAGInoEshirt"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "UNAGInoEshirt"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "UNAGInoEshirt"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "UNAGInoEshirt"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "UNAGInoEshirt"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "UNAGInoEshirt"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi simplesuit, UNAGInoEshirt"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "UNAGInoSDs"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "UNAGInoSDs"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "UNAGInoSDs"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "UNAGInoSDs"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "UNAGInoSDs"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "UNAGInoSDs"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "UNAGInoSDs"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "UNAGInoSDs"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi simplesuit, UNAGInoSDs"

  @requires:wdi.realistic.bodies @requires:nelim.pickletools.screenshotstudio @requires:nelim.pickletools.colonistrace @requires:UNAGI.Wahuu.hako
  Scenario: UNAGI Japanese Assortment on ten bodies
    Given Nelim's Sanctuary: the animals are removed from the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: the other colonists are out of frame
    And a colonist "M-Thin" exists
    And "M-Thin" gender is male
    And Nelim's Pickle Tools: "M-Thin" body type is Thin
    And a colonist "M-Avg" exists
    And "M-Avg" gender is male
    And Nelim's Pickle Tools: "M-Avg" body type is Male
    And a colonist "M-Fat" exists
    And "M-Fat" gender is male
    And Nelim's Pickle Tools: "M-Fat" body type is Fat
    And a colonist "M-Hulk" exists
    And "M-Hulk" gender is male
    And Nelim's Pickle Tools: "M-Hulk" body type is Hulk
    And a colonist "M-Kid" exists
    And "M-Kid" is 8 years old
    And "M-Kid" gender is male
    And Nelim's Pickle Tools: "M-Kid" body type is Child
    And a colonist "F-Thin" exists
    And "F-Thin" gender is female
    And Nelim's Pickle Tools: "F-Thin" body type is Thin
    And a colonist "F-Avg" exists
    And "F-Avg" gender is female
    And Nelim's Pickle Tools: "F-Avg" body type is Female
    And a colonist "F-Fat" exists
    And "F-Fat" gender is female
    And Nelim's Pickle Tools: "F-Fat" body type is Fat
    And a colonist "F-Hulk" exists
    And "F-Hulk" gender is female
    And Nelim's Pickle Tools: "F-Hulk" body type is Hulk
    And a colonist "F-Kid" exists
    And "F-Kid" is 8 years old
    And "F-Kid" gender is female
    And Nelim's Pickle Tools: "F-Kid" body type is Child
    And Nelim's Pickle Tools: "M-Thin" stands at (196, 186) facing South
    And I draft "M-Thin"
    And Nelim's Pickle Tools: "M-Avg" stands at (198, 186) facing South
    And I draft "M-Avg"
    And Nelim's Pickle Tools: "M-Fat" stands at (200, 186) facing South
    And I draft "M-Fat"
    And Nelim's Pickle Tools: "M-Hulk" stands at (202, 186) facing South
    And I draft "M-Hulk"
    And Nelim's Pickle Tools: "M-Kid" stands at (204, 186) facing South
    And I draft "M-Kid"
    And Nelim's Pickle Tools: "F-Thin" stands at (196, 184) facing South
    And I draft "F-Thin"
    And Nelim's Pickle Tools: "F-Avg" stands at (198, 184) facing South
    And I draft "F-Avg"
    And Nelim's Pickle Tools: "F-Fat" stands at (200, 184) facing South
    And I draft "F-Fat"
    And Nelim's Pickle Tools: "F-Hulk" stands at (202, 184) facing South
    And I draft "F-Hulk"
    And Nelim's Pickle Tools: "F-Kid" stands at (204, 184) facing South
    And I draft "F-Kid"
    When I destroy the gear of "M-Thin"
    And I destroy the gear of "M-Avg"
    And I destroy the gear of "M-Fat"
    And I destroy the gear of "M-Hulk"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And I destroy the gear of "F-Avg"
    And I destroy the gear of "F-Fat"
    And I destroy the gear of "F-Hulk"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: studio presentation mode is enabled
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi japanese assortment, bare"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "UNAwasitagi"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "UNAwasitagi"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "UNAwasitagi"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "UNAwasitagi"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "UNAwasitagi"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "UNAwasitagi"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "UNAwasitagi"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "UNAwasitagi"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi japanese assortment, UNAwasitagi"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_UNAwahaori"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_UNAwahaori"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_UNAwahaori"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_UNAwahaori"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_UNAwahaori"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_UNAwahaori"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_UNAwahaori"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_UNAwahaori"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi japanese assortment, Apparel_UNAwahaori"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "UNAkariginu"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "UNAkariginu"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "UNAkariginu"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "UNAkariginu"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "UNAkariginu"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "UNAkariginu"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "UNAkariginu"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "UNAkariginu"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi japanese assortment, UNAkariginu"

  @requires:wdi.realistic.bodies @requires:nelim.pickletools.screenshotstudio @requires:nelim.pickletools.colonistrace @requires:UNAGI.Cafe.gohan
  Scenario: UNAGI CAFE on ten bodies
    Given Nelim's Sanctuary: the animals are removed from the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: the other colonists are out of frame
    And a colonist "M-Thin" exists
    And "M-Thin" gender is male
    And Nelim's Pickle Tools: "M-Thin" body type is Thin
    And a colonist "M-Avg" exists
    And "M-Avg" gender is male
    And Nelim's Pickle Tools: "M-Avg" body type is Male
    And a colonist "M-Fat" exists
    And "M-Fat" gender is male
    And Nelim's Pickle Tools: "M-Fat" body type is Fat
    And a colonist "M-Hulk" exists
    And "M-Hulk" gender is male
    And Nelim's Pickle Tools: "M-Hulk" body type is Hulk
    And a colonist "M-Kid" exists
    And "M-Kid" is 8 years old
    And "M-Kid" gender is male
    And Nelim's Pickle Tools: "M-Kid" body type is Child
    And a colonist "F-Thin" exists
    And "F-Thin" gender is female
    And Nelim's Pickle Tools: "F-Thin" body type is Thin
    And a colonist "F-Avg" exists
    And "F-Avg" gender is female
    And Nelim's Pickle Tools: "F-Avg" body type is Female
    And a colonist "F-Fat" exists
    And "F-Fat" gender is female
    And Nelim's Pickle Tools: "F-Fat" body type is Fat
    And a colonist "F-Hulk" exists
    And "F-Hulk" gender is female
    And Nelim's Pickle Tools: "F-Hulk" body type is Hulk
    And a colonist "F-Kid" exists
    And "F-Kid" is 8 years old
    And "F-Kid" gender is female
    And Nelim's Pickle Tools: "F-Kid" body type is Child
    And Nelim's Pickle Tools: "M-Thin" stands at (196, 186) facing South
    And I draft "M-Thin"
    And Nelim's Pickle Tools: "M-Avg" stands at (198, 186) facing South
    And I draft "M-Avg"
    And Nelim's Pickle Tools: "M-Fat" stands at (200, 186) facing South
    And I draft "M-Fat"
    And Nelim's Pickle Tools: "M-Hulk" stands at (202, 186) facing South
    And I draft "M-Hulk"
    And Nelim's Pickle Tools: "M-Kid" stands at (204, 186) facing South
    And I draft "M-Kid"
    And Nelim's Pickle Tools: "F-Thin" stands at (196, 184) facing South
    And I draft "F-Thin"
    And Nelim's Pickle Tools: "F-Avg" stands at (198, 184) facing South
    And I draft "F-Avg"
    And Nelim's Pickle Tools: "F-Fat" stands at (200, 184) facing South
    And I draft "F-Fat"
    And Nelim's Pickle Tools: "F-Hulk" stands at (202, 184) facing South
    And I draft "F-Hulk"
    And Nelim's Pickle Tools: "F-Kid" stands at (204, 184) facing South
    And I draft "F-Kid"
    When I destroy the gear of "M-Thin"
    And I destroy the gear of "M-Avg"
    And I destroy the gear of "M-Fat"
    And I destroy the gear of "M-Hulk"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And I destroy the gear of "F-Avg"
    And I destroy the gear of "F-Fat"
    And I destroy the gear of "F-Hulk"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: studio presentation mode is enabled
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi cafe, bare"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "UNAcafe_wanpi"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "UNAcafe_wanpi"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "UNAcafe_wanpi"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "UNAcafe_wanpi"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "UNAcafe_wanpi"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "UNAcafe_wanpi"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "UNAcafe_wanpi"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "UNAcafe_wanpi"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi cafe, UNAcafe_wanpi"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_UNAcafe_epuron"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_UNAcafe_epuron"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_UNAcafe_epuron"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_UNAcafe_epuron"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_UNAcafe_epuron"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_UNAcafe_epuron"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_UNAcafe_epuron"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_UNAcafe_epuron"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, unagi cafe, Apparel_UNAcafe_epuron"

  @requires:wdi.realistic.bodies @requires:nelim.pickletools.screenshotstudio @requires:nelim.pickletools.colonistrace @requires:BBIS.MaidProject
  Scenario: Maid Project on ten bodies
    Given Nelim's Sanctuary: the animals are removed from the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: the other colonists are out of frame
    And a colonist "M-Thin" exists
    And "M-Thin" gender is male
    And Nelim's Pickle Tools: "M-Thin" body type is Thin
    And a colonist "M-Avg" exists
    And "M-Avg" gender is male
    And Nelim's Pickle Tools: "M-Avg" body type is Male
    And a colonist "M-Fat" exists
    And "M-Fat" gender is male
    And Nelim's Pickle Tools: "M-Fat" body type is Fat
    And a colonist "M-Hulk" exists
    And "M-Hulk" gender is male
    And Nelim's Pickle Tools: "M-Hulk" body type is Hulk
    And a colonist "M-Kid" exists
    And "M-Kid" is 8 years old
    And "M-Kid" gender is male
    And Nelim's Pickle Tools: "M-Kid" body type is Child
    And a colonist "F-Thin" exists
    And "F-Thin" gender is female
    And Nelim's Pickle Tools: "F-Thin" body type is Thin
    And a colonist "F-Avg" exists
    And "F-Avg" gender is female
    And Nelim's Pickle Tools: "F-Avg" body type is Female
    And a colonist "F-Fat" exists
    And "F-Fat" gender is female
    And Nelim's Pickle Tools: "F-Fat" body type is Fat
    And a colonist "F-Hulk" exists
    And "F-Hulk" gender is female
    And Nelim's Pickle Tools: "F-Hulk" body type is Hulk
    And a colonist "F-Kid" exists
    And "F-Kid" is 8 years old
    And "F-Kid" gender is female
    And Nelim's Pickle Tools: "F-Kid" body type is Child
    And Nelim's Pickle Tools: "M-Thin" stands at (196, 186) facing South
    And I draft "M-Thin"
    And Nelim's Pickle Tools: "M-Avg" stands at (198, 186) facing South
    And I draft "M-Avg"
    And Nelim's Pickle Tools: "M-Fat" stands at (200, 186) facing South
    And I draft "M-Fat"
    And Nelim's Pickle Tools: "M-Hulk" stands at (202, 186) facing South
    And I draft "M-Hulk"
    And Nelim's Pickle Tools: "M-Kid" stands at (204, 186) facing South
    And I draft "M-Kid"
    And Nelim's Pickle Tools: "F-Thin" stands at (196, 184) facing South
    And I draft "F-Thin"
    And Nelim's Pickle Tools: "F-Avg" stands at (198, 184) facing South
    And I draft "F-Avg"
    And Nelim's Pickle Tools: "F-Fat" stands at (200, 184) facing South
    And I draft "F-Fat"
    And Nelim's Pickle Tools: "F-Hulk" stands at (202, 184) facing South
    And I draft "F-Hulk"
    And Nelim's Pickle Tools: "F-Kid" stands at (204, 184) facing South
    And I draft "F-Kid"
    When I destroy the gear of "M-Thin"
    And I destroy the gear of "M-Avg"
    And I destroy the gear of "M-Fat"
    And I destroy the gear of "M-Hulk"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And I destroy the gear of "F-Avg"
    And I destroy the gear of "F-Fat"
    And I destroy the gear of "F-Hulk"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: studio presentation mode is enabled
    And I wait 90 ticks
    And I take a screenshot "wardrobe, maid project, bare"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "ChefMaid"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "ChefMaid"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "ChefMaid"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "ChefMaid"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "ChefMaid"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "ChefMaid"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "ChefMaid"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "ChefMaid"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, maid project, ChefMaid"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "CleanerMaid"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "CleanerMaid"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "CleanerMaid"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "CleanerMaid"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "CleanerMaid"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "CleanerMaid"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "CleanerMaid"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "CleanerMaid"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, maid project, CleanerMaid"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "FightMaid"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "FightMaid"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "FightMaid"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "FightMaid"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "FightMaid"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "FightMaid"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "FightMaid"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "FightMaid"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, maid project, FightMaid"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "NurseMaid"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "NurseMaid"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "NurseMaid"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "NurseMaid"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "NurseMaid"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "NurseMaid"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "NurseMaid"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "NurseMaid"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "wardrobe, maid project, NurseMaid"
