# Wardrobe: clothing libraries on the ten bodies of the gallery, bare then dressed, one scenario per mod. Generated by gen-wardrobe.js; do not edit by hand.
# Every image is opened and read: the question is whether the garment looks right on the body, with and without this mod's cut.
# Pass: wsl-deps.wardrobe.map.
@review @refit @timeout:300
Feature: clothing libraries on the ten bodies

  Background:
    Given the save "Nelims-tribe" is loaded

  @requires:wdi.realistic.bodies @requires:nelim.pickletools.screenshotstudio @requires:nelim.pickletools.colonistrace @requires:LoneKin.ChildrenWearAnything
  Scenario: Vanilla garments without WDI art on ten bodies
    Given Nelim's Sanctuary: the animals are removed from the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: the other colonists are out of frame
    And a colonist "M-Thin" exists
    And "M-Thin" gender is male
    And Nelim's Pickle Tools: "M-Thin" body type is Thin
    And a colonist "M-Avg" exists
    And "M-Avg" gender is male
    And Nelim's Pickle Tools: "M-Avg" body type is Male
    And a colonist "M-Fat" exists
    And "M-Fat" gender is male
    And Nelim's Pickle Tools: "M-Fat" body type is Fat
    And a colonist "M-Hulk" exists
    And "M-Hulk" gender is male
    And Nelim's Pickle Tools: "M-Hulk" body type is Hulk
    And a colonist "M-Kid" exists
    And "M-Kid" is 8 years old
    And "M-Kid" gender is male
    And Nelim's Pickle Tools: "M-Kid" body type is Child
    And a colonist "F-Thin" exists
    And "F-Thin" gender is female
    And Nelim's Pickle Tools: "F-Thin" body type is Thin
    And a colonist "F-Avg" exists
    And "F-Avg" gender is female
    And Nelim's Pickle Tools: "F-Avg" body type is Female
    And a colonist "F-Fat" exists
    And "F-Fat" gender is female
    And Nelim's Pickle Tools: "F-Fat" body type is Fat
    And a colonist "F-Hulk" exists
    And "F-Hulk" gender is female
    And Nelim's Pickle Tools: "F-Hulk" body type is Hulk
    And a colonist "F-Kid" exists
    And "F-Kid" is 8 years old
    And "F-Kid" gender is female
    And Nelim's Pickle Tools: "F-Kid" body type is Child
    And Nelim's Pickle Tools: "M-Thin" stands at (196, 186) facing South
    And I draft "M-Thin"
    And Nelim's Pickle Tools: "M-Avg" stands at (198, 186) facing South
    And I draft "M-Avg"
    And Nelim's Pickle Tools: "M-Fat" stands at (200, 186) facing South
    And I draft "M-Fat"
    And Nelim's Pickle Tools: "M-Hulk" stands at (202, 186) facing South
    And I draft "M-Hulk"
    And Nelim's Pickle Tools: "M-Kid" stands at (204, 186) facing South
    And I draft "M-Kid"
    And Nelim's Pickle Tools: "F-Thin" stands at (196, 184) facing South
    And I draft "F-Thin"
    And Nelim's Pickle Tools: "F-Avg" stands at (198, 184) facing South
    And I draft "F-Avg"
    And Nelim's Pickle Tools: "F-Fat" stands at (200, 184) facing South
    And I draft "F-Fat"
    And Nelim's Pickle Tools: "F-Hulk" stands at (202, 184) facing South
    And I draft "F-Hulk"
    And Nelim's Pickle Tools: "F-Kid" stands at (204, 184) facing South
    And I draft "F-Kid"
    When I destroy the gear of "M-Thin"
    And I destroy the gear of "M-Avg"
    And I destroy the gear of "M-Fat"
    And I destroy the gear of "M-Hulk"
    And I destroy the gear of "M-Kid"
    And I destroy the gear of "F-Thin"
    And I destroy the gear of "F-Avg"
    And I destroy the gear of "F-Fat"
    And I destroy the gear of "F-Hulk"
    And I destroy the gear of "F-Kid"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And Nelim's Pickle Tools: studio presentation mode is enabled
    And I wait 90 ticks
    And I take a screenshot "refit, vanilla garments without wdi art, bare"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_Jacket"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_Jacket"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_Jacket"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_Jacket"
    And I destroy the gear of "M-Kid"
    And Nelim's Pickle Tools: "M-Kid" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Kid" wears "Apparel_Jacket"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_Jacket"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_Jacket"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_Jacket"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_Jacket"
    And I destroy the gear of "F-Kid"
    And Nelim's Pickle Tools: "F-Kid" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Kid" wears "Apparel_Jacket"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "refit, vanilla garments without wdi art, Apparel_Jacket"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_Parka"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_Parka"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_Parka"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_Parka"
    And I destroy the gear of "M-Kid"
    And Nelim's Pickle Tools: "M-Kid" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Kid" wears "Apparel_Parka"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_Parka"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_Parka"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_Parka"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_Parka"
    And I destroy the gear of "F-Kid"
    And Nelim's Pickle Tools: "F-Kid" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Kid" wears "Apparel_Parka"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "refit, vanilla garments without wdi art, Apparel_Parka"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_Duster"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_Duster"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_Duster"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_Duster"
    And I destroy the gear of "M-Kid"
    And Nelim's Pickle Tools: "M-Kid" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Kid" wears "Apparel_Duster"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_Duster"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_Duster"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_Duster"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_Duster"
    And I destroy the gear of "F-Kid"
    And Nelim's Pickle Tools: "F-Kid" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Kid" wears "Apparel_Duster"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "refit, vanilla garments without wdi art, Apparel_Duster"
    And I destroy the gear of "M-Thin"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Thin" wears "Apparel_FlakVest"
    And I destroy the gear of "M-Avg"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Avg" wears "Apparel_FlakVest"
    And I destroy the gear of "M-Fat"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Fat" wears "Apparel_FlakVest"
    And I destroy the gear of "M-Hulk"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Hulk" wears "Apparel_FlakVest"
    And I destroy the gear of "M-Kid"
    And Nelim's Pickle Tools: "M-Kid" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "M-Kid" wears "Apparel_FlakVest"
    And I destroy the gear of "F-Thin"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Thin" wears "Apparel_FlakVest"
    And I destroy the gear of "F-Avg"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Avg" wears "Apparel_FlakVest"
    And I destroy the gear of "F-Fat"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Fat" wears "Apparel_FlakVest"
    And I destroy the gear of "F-Hulk"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Hulk" wears "Apparel_FlakVest"
    And I destroy the gear of "F-Kid"
    And Nelim's Pickle Tools: "F-Kid" wears "Apparel_Pants"
    And Nelim's Pickle Tools: "F-Kid" wears "Apparel_FlakVest"
    And Nelim's Sanctuary: I am at the sanctuary "calm-zone-close"
    And I wait 90 ticks
    And I take a screenshot "refit, vanilla garments without wdi art, Apparel_FlakVest"
