// node gen-facings.js : writes 10-facings.feature, the gallery scenario of 05-gallery.feature played with the ten bodies facing East, then North
// (the south captures are the gallery's own). Generated: do not edit by hand.
const fs = require('fs');
const g = fs.readFileSync(__dirname + '/05-gallery.feature', 'utf8').replace(/\r\n/g, '\n').split('\n');
const start = g.findIndex(l => /^\s*@requires:/.test(l));
const body = g.slice(start);
const o = ['# The fitting seen from the side and from behind: the ten bodies of the gallery facing East, then North. Generated by gen-facings.js. Pass: wsl-deps.gallery.map (or gallery-notm).',
  '@review @facings @timeout:300', 'Feature: the fitting, seen from the side and from behind', '', '  Background:', '    Given the save "Nelims-tribe" is loaded', ''];
for (const f of ['East', 'North']) {
  const names = ['M-Thin','M-Avg','M-Fat','M-Hulk','M-Kid','F-Thin','F-Avg','F-Fat','F-Hulk','F-Kid'];
  body.forEach(l => { if (/I take a screenshot/.test(l)) { names.forEach(n => o.push('    And Nelim\'s Pickle Tools: "' + n + '" faces ' + f)); o.push('    And I wait 2 ticks'); } o.push(l.replace(/facing South/g, 'facing ' + f).replace(/Scenario: ten bodies, four outfits/, 'Scenario: ten bodies, four outfits, facing ' + f.toLowerCase()).replace(/screenshot "gallery, the fitting, /, 'screenshot "facings, ' + f.toLowerCase() + ', ')); });
  o.push('');
}
fs.writeFileSync(__dirname + '/10-facings.feature', o.join('\n'));
console.log('wrote 10-facings.feature');
